package main

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/prutwee/semnautics/internal/mapreduce"
	"github.com/prutwee/semnautics/pkg/types"
)

func main() {
	fmt.Println("Starting Semnautics Engine...")

	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()

	ingestChan := make(chan types.Event, 50000)
	mapperOutChan := make(chan types.MappedRecord, 50000)

	// mod, this will be dynamically generated by the A* DAG.
	mapFunc := func(event types.Event) ([]types.MappedRecord, error) {
		// Mock logic: If the payload is empty, pretend it's a $100 checkout in California (Hash 42)
		// If we had bytes, we would parse JSON/Protobuf here.
		return []types.MappedRecord{
			{
				DimensionHash: 42, // e.g., hash("State: California")
				Value:         100.00,
				Operation:     event.Operation,
			},
		}, nil
	}

	mapperPool := mapreduce.NewMapperPool(4, mapFunc) // 4 concurrent workers

	shuffler, err := mapreduce.NewShuffler(8, 10000) // 8 partitions (MUST be a power of 2)
	if err != nil {
		panic(err)
	}

	reducerPool := mapreduce.NewReducerPool(shuffler.GetPartitions())

	reducerPool.Start(ctx)
	shuffler.Start(ctx, mapperOutChan)
	mapperPool.Start(ctx, ingestChan, mapperOutChan)

	go mockDatabaseStream(ingestChan)

	sigs := make(chan os.Signal, 1)
	signal.Notify(sigs, syscall.SIGINT, syscall.SIGTERM)

	fmt.Println("Pipeline running. Press Ctrl+C to shut down and view results.")
	<-sigs

	fmt.Println("\nInitiating graceful shutdown...")

	cancel()

	time.Sleep(500 * time.Millisecond)

	reducerPool.PrintMetrics()
}

// mockDatabaseStream simulates a CDC stream blasting 100,000 events into the engine.
func mockDatabaseStream(out chan<- types.Event) {
	fmt.Println("Mock DB: Blasting 100,000 events into the engine...")

	start := time.Now()
	for i := 0; i < 100000; i++ {
		out <- types.Event{
			Operation: types.OpInsert,
			// Payload is omitted for this mock test to save memory allocation
		}
	}

	fmt.Printf("Mock DB: Finished pushing 100,000 events in %v\n", time.Since(start))
}
